name: MatrixCacheDemo

on:
  workflow_dispatch:

jobs:
  MatrixCacheDemo:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4.1.0

      - name: Set Required repositories PS Core
        shell: pwsh
        run: |
          cd test/Dependencies
          ./Register-TestRepository.ps1

      - name: Cache modules
        id: psmodulecache
        uses: ./
        with:
          modules-to-cache: PlatyPS,microsoft.powershell.secretmanagement,PSModuleCache\Duplicate,ActiveDirectoryCmdlets:22.0.8462.1
          modules-to-cache-prerelease: PnP.PowerShell::,pester:5.3.0-rc1
          shell: powershell,pwsh
          updatable: "true"
          prefixidentifier: "true"

      - name: Get required modules on Windows PowerShell
        shell: pwsh
        run: |
          'PlatyPS','microsoft.powershell.secretmanagement','Duplicate','PnP.PowerShell'|
            Foreach-Object {
              Import-Module $_
              Write-Host "$_ '$(Get-Module $_ -ListAvailabLe|Select-Object Name,Version,@{Name='PreRelease';e={$_.PrivateData.PSData.Prerelease}},RepositorySourceLocation)'"
           }
