name: UbuntuRestoreCacheOnPsCore
on:
  workflow_dispatch:

jobs:
  RestoreCacheOnPsCore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: PSDeploy, BuildHelpers, PlAtYpS, Pester:5.0.2, EZOut
          shell: pwsh

      - name: Show the previous action works
        shell: pwsh
        run: |
          Get-Module -Name PSDeploy, BuildHelpers, PlAtYpS, EZOut -ListAvailable